spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: myCompany

# Mostrar Queries MongoDB no Terminal:
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
