version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
